### ISSUE TITLE
Discussion : Laravel Installation or Use

### ISSUE THREAD

**Issue by varadpoddar** [adorableio/avatars-api-middleware#83]
Hi, I was wondering if there was a way to integrate this in Laravel. 👍

**Comment by rylnd** [comment]
Hi @varadpoddar! I'm not familiar with Laravel but it looks to have a lot of overlap with [express.js](https://expressjs.com/), for which this project is a middleware.

Conceptually, the shortest path to your request would be to run both application servers on your backend: a PHP server running your laravel app, and a node.js server running this avatars API as an express app.

Because of the aforementioned conceptual overlap between the two libraries I couldn't find any perfect examples for you, but [LaraSocial](https://github.com/msalom28/Larasocial) seems to include a node.js server within a Laravel app (see the [server.js](https://github.com/msalom28/Larasocial/blob/master/server.js) entrypoint).

I hope this helps! GitHub issues are specific to issues with the library itself, so if you have further questions about how to generally integrate Laravel and express.js I would look to the StackOverflow community for answers.
