### ISSUE TITLE
module.exports missing

### ISSUE THREAD

**Issue by agamemnus** [adorableio/avatars-api-middleware#86]
idk

Needed to add `module.exports = router;` after `var router = (0, _express2.default)();` in `dist/routes/avatars.js`.

**Comment by rylnd** [comment]
@agamemnus sorry for the late response; holidays and all that. 

We've mainly been using this with babel and using `import` so we hadn't noticed the issue! It looks like what you're experiencing is described [here](https://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default).

Instead of modifying the source code, you should also be able to use:

```javascript
var middleware = require('adorable-avatars').default;
```

Could you verify that when you have a moment?

I"m going to leave this open until we've fixed the issue; I believe something as simple as https://www.npmjs.com/package/babel-plugin-add-module-exports should do the trick.

**Comment by agamemnus** [comment]
I tried that and it didn't work, I think. I ended up just using your server code wholesale. Thank you for sharing this avatar generator!

**Comment by agamemnus** [comment]
But if I have time I will try it again.

**Comment by rylnd** [comment]
@agamemnus sure thing; I was playing with it in runkit and found that to be the case: https://runkit.com/rylnd/5c378920bc4c1d0013310b67

**Comment by rylnd** [comment]
@agamemnus as you probably saw, 0.2.2 was just released. The intention is that it should address this problem; please reopen the issue if it does not.
